package org.example;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;

public class Main {
    public static void main(String[] args) {
        var apartmentList = List.of(
                Apartment.builder()
                        .streetName("1-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(80)
                        .livingSpace(80)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(true)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Иван")
                                                .lastName("Иванов")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("2-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(60)
                        .livingSpace(60)
                        .numberOfRooms(3)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(false)
                        .hasParkingLot(false)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Алексей")
                                                .lastName("Алексеев")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("3-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(70)
                        .livingSpace(70)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(false)
                        .hasParkingLot(true)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Мария")
                                                .lastName("Петрова")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("4-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(100)
                        .livingSpace(100)
                        .numberOfRooms(5)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(false)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Антон")
                                                .lastName("Иванов")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("5-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(40)
                        .livingSpace(40)
                        .numberOfRooms(2)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(true)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Абрам")
                                                .lastName("Козырев")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("6-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(65)
                        .livingSpace(65)
                        .numberOfRooms(3)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(false)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Алена")
                                                .lastName("Солнышко")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("7-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(75)
                        .livingSpace(75)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(true)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Райан")
                                                .lastName("Гослинг")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("8-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(95)
                        .livingSpace(95)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(false)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Йозеф")
                                                .lastName("Швейк")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("9-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(80)
                        .livingSpace(80)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(true)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Индржих")
                                                .lastName("Лукаш")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("10-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(77)
                        .livingSpace(77)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(false)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Вернон")
                                                .lastName("Роше")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("11-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(87)
                        .livingSpace(87)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(true)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Эредин")
                                                .lastName("Гласс")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build(),
                Apartment.builder()
                        .streetName("12-я улица")
                        .buildingNumber(1)
                        .apartmentNumber(25)
                        .overallSpace(55)
                        .livingSpace(55)
                        .numberOfRooms(4)
                        .floor(6)
                        .hasElevator(true)
                        .hasConcierge(true)
                        .hasParkingLot(false)
                        .hasPrivateArea(true)
                        .previousOwners(
                                List.of(Resident.builder()
                                                .firstName("Вася")
                                                .lastName("Пупкин")
                                                .birthDate("01.01.1990")
                                                .build(),
                                        Resident.builder()
                                                .firstName("Петр")
                                                .lastName("Петров")
                                                .birthDate("02.03.1990")
                                                .build())
                        )
                        .residents(
                                Map.of(Resident.builder()
                                                .firstName("Аксель")
                                                .lastName("Эспарза")
                                                .birthDate("02.02.1991").build(),
                                        "31.12.2030")
                        )
                        .build()
        );

        var objectMapper = new ObjectMapper();
        try {
            objectMapper.writeValue(new File("apartments.json"), apartmentList);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        try {
            var apartmentsFromJson = objectMapper.readValue(
                    new File("apartments.json"), new TypeReference<List<Apartment>>() {
                    }
            );
            System.out.println("Прописанные люди:");
            apartmentsFromJson.stream()
                    .map(Apartment::getResidents)
                    .forEach(System.out::println);
            System.out.println("Квартиры с парковками:");
            apartmentsFromJson.stream()
                    .filter(Apartment::isHasParkingLot)
                    .forEach(System.out::println);
            System.out.println("Сортировка квартир по площади:");
            apartmentsFromJson.stream()
                    .sorted(new ApartmentSpaceComparator())
                    .forEach(System.out::println);
            System.out.println("Квартиры с 4-мя комнатами:");
            apartmentsFromJson.stream()
                    .filter(apartment -> apartment.getNumberOfRooms() == 4)
                    .forEach(System.out::println);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}